# Build script
init:
  - git config --global core.autocrlf true

# Install services
services:
  - iis

install:
- ps: Install-WindowsFeature -Name AS-WAS-Support
- ps: Start-Service W3SVC
- ps: Start-Service WAS

# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "AppVeyor"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - main
